#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width            2
bspc config window_gap              10

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         false
bspc config single_monocle          true

# keyboard layout
setxkbmap -layout pl -option caps:escape &

# compositor and status
#compton -b --backend glx --vsync opengl-swc --xrender-sync --xrender-sync-fence --paint-on-overlay &
compton -b --config ~/.config/compton/compton.conf &
polybar perfect -q &
feh --bg-scale -z ~/Wallpapers &
