#! /bin/sh

# steal colours from xresources
xrdb ~/.Xresources
FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
GRAY=$(xrdb -query | grep 'color8:'| awk '{print $NF}')


sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width            1
bspc config window_gap              10

bspc config focused_border_color    $GREEN 
bspc config normal_border_color     $GRAY
bspc config active_border_color     $BLUE
bspc config presel_feedback_color   $GRAY

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         false
bspc config single_monocle          true

# keyboard layout
setxkbmap -layout pl -option caps:escape &

# compositor and status
compton -b --config ~/.config/compton/compton.conf &
~/.config/polybar/launch.sh
feh --bg-scale -z ~/Wallpapers &
