#!/bin/bash

#constants
BAT_LOC='/sys/class/power_supply/BAT'
CHARGING=""
FULL=" 100%"
RAMP_0=""
RAMP_1=""
RAMP_2=""
RAMP_3=""
RAMP_4=""

main() {
    probe_batteries
    get_battery_status
    show_battery_info
}

probe_batteries() {
    BAT_0_STAT=$(cat ${BAT_LOC}0/status)
    BAT_0_ENERGY=$(cat ${BAT_LOC}0/energy_now)
    BAT_0_FULL=$(cat ${BAT_LOC}0/energy_full)
    BAT_0_POWER=$(cat ${BAT_LOC}0/power_now)

    if [[ -d ${BAT_LOC}1 ]]; then
    BAT_1_STAT=$(cat ${BAT_LOC}1/status)
    BAT_1_ENERGY=$(cat ${BAT_LOC}1/energy_now)
    BAT_1_FULL=$(cat ${BAT_LOC}1/energy_full)
    BAT_1_POWER=$(cat ${BAT_LOC}1/power_now)
    fi
}

get_battery_status() {
    if [[ $BAT_1_STAT ]]; then
        #We are docked
        ENERGY_FULL=$(( $BAT_0_FULL + $BAT_1_FULL ))
        ENERGY=$(( $BAT_0_ENERGY + $BAT_1_ENERGY ))
        if [[ $BAT_0_STAT == Discharging ]]; then
            STATUS="Discharging"
            POWER=$BAT_0_POWER
        elif [[ $BAT_1_STAT == Discharging ]]; then
            STATUS="Discharging"
            POWER=$BAT_1_POWER
        elif [[ $BAT_0_STAT == Charging || $BAT_1_STAT == Charging ]]; then
            STATUS="Charging"
            POWER=$BAT_0_POWER
        else 
            STATUS="Discharging"
            POWER=$BAT_0_POWER
        fi
    else
        STATUS=$BAT_0_STAT
        ENERGY_FULL=$BAT_0_FULL
        ENERGY=$BAT_0_ENERGY
        POWER=$BAT_0_POWER
    fi

    if (( $ENERGY_FULL == 0 )); then
        # ACPI is not working properly at the moment
        exit
    fi

    PERC=$(( $ENERGY * 100 / $ENERGY_FULL ))

    if (( $PERC >= 98 )); then
        STATUS=Full
    fi
}

show_battery_info() {
    if [[ $STATUS == Full ]]; then
        echo $FULL
    elif [[ $STATUS == Charging ]]; then
        echo "$CHARGING $PERC%"
    elif [[ $STATUS == Discharging ]]; then
        if (( $POWER == 0 )); then
            exit
        fi

        TIME_LEFT=$(( $ENERGY * 3600 / $POWER ))
        TIME_LEFT=$(date -d "1 jan 1970 + $TIME_LEFT seconds" +%H:%M)

        if (( $PERC > 85 )); then
            ICON=$RAMP_4
        elif (( $PERC > 60 )); then
            ICON=$RAMP_3
        elif (( $PERC > 40 )); then
            ICON=$RAMP_2
        elif (( $PERC > 20 )); then
            ICON=$RAMP_1
        else
            ICON=$RAMP_0
        fi

        echo "$ICON $PERC% ($TIME_LEFT)"
    fi
}

main

